apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wkh4mybog-python
  janus-idp.io/tekton: wkh4mybog-python
  backstage.io/kubernetes-id: wkh4mybog-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wkh4mybog-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
